# Generated by Django 4.0.4 on 2022-08-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_options_chat_last_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-last_active',)},
        ),
    ]
