export const TRY_LOGIN = "TRY_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const TRY_REGISTER = "TRY_REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"

export const BASE_URL = 'http://localhost:8001/'

export const LOGOUT = "LOGOUT"

export const GET_FRIEND_LIST_SUCCESS = "GET_FRIEND_LIST_SUCCESS"


export const GET_INVITATIONS_SUCCESS = "GET_INVITATIONS_SUCCESS"


export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS"

export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS"

export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS"

export const SEARCH_FRIENDS_SUCCESS = "SEARCH_FRIENDS_SUCCESS"

export const CREATE_NEW_CHAT_SUCCESS = "CREATE_NEW_CHAT_SUCCESS"

export const DELETE_MESSAGES = "DELETE_MESSAGES"

export const ERROR = "ERROR"
export const LOADING = "LOADING"
export const STOP_LOADING = "STOP_LOADING"