export const TRY_LOGIN = "TRY_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const TRY_REGISTER = "TRY_REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"

export const BASE_URL = 'http://localhost:8000/'

export const LOGOUT = "LOGOUT"

export const GET_FRIEND_LIST = "GET_FRIEND_LIST"
export const GET_FRIEND_LIST_ERROR = "GET_FRIEND_LIST_ERROR"
export const GET_FRIEND_LIST_SUCCESS = "GET_FRIEND_LIST_SUCCESS"

export const GET_INVITATIONS = "GET_INVITATIONS"
export const GET_INVITATIONS_SUCCESS = "GET_INVITATIONS_SUCCESS"
export const GET_INVITATIONS_ERROR = "GET_INVITATIONS_ERROR"

export const ACCEPT_INVITATION = "ACCEPT_INVITATION"
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS"
export const ACCEPT_INVITATION_ERROR = "ACCEPT_INVITATION_ERROR"

export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST"
export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS"
export const SEND_FRIEND_REQUEST_ERROR = "SEND_FRIEND_REQUEST_ERROR"

export const GET_CHATS = "GET_CHATS"
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS"
export const GET_CHATS_ERROR = "GET_CHATS_ERROR"

export const SEARCH_FRIENDS = "SEARCH_FRIENDS"
export const SEARCH_FRIENDS_SUCCESS = "SEARCH_FRIENDS_SUCCESS"
export const SEARCH_FRIENDS_ERROR = "SEARCH_FRIENDS_ERROR"

export const DELETE_ERRORS = "DELETE_ERRORS"

export const DELETE_MESSAGES = "DELETE_MESSAGES"